<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Customer;
use App\Models\Employee;
use App\Models\Outlet;

class ReviewerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Add note: static OTP for reviewer can be configured via REVIEWER_STATIC_OTP environment variable

        // 1. Setup Demo Customer for Reviewer
        $reviewerCustomerUser = User::firstOrCreate(
            ['email' => 'reviewer.customer@washwallet.com'],
            [
                'name' => 'Reviewer Customer',
                'password' => Hash::make(env('REVIEWER_PASSWORD', 'password123')),
                'email_verified_at' => now(),
            ]
        );

        $customer = Customer::firstOrCreate(
            ['user_id' => $reviewerCustomerUser->id],
            [
                'phone' => '081234567890',
                'address' => 'Reviewer Street No. 1'
            ]
        );

        // 2. Ensure an Outlet exists
        $outlet = Outlet::first();
        if (!$outlet) {
            $outlet = Outlet::create([
                'name' => 'Reviewer Demo Outlet',
                'address' => 'Reviewer Street No. 2',
                'phone' => '081234567891'
            ]);
        }

        // 3. Setup Demo Cashier for Reviewer
        $reviewerCashierUser = User::firstOrCreate(
            ['email' => 'reviewer.cashier@washwallet.com'],
            [
                'name' => 'Reviewer Cashier',
                'password' => Hash::make(env('REVIEWER_PASSWORD', 'password123')),
                'email_verified_at' => now(),
            ]
        );

        Employee::firstOrCreate(
            ['user_id' => $reviewerCashierUser->id],
            [
                'outlet_id' => $outlet->id,
                'phone' => '081234567892',
                // Add required employee specific fields here based on your actual schema
            ]
        );

        // 4. Setup Demo Production for Reviewer
        $reviewerProductionUser = User::firstOrCreate(
            ['email' => 'reviewer.production@washwallet.com'],
            [
                'name' => 'Reviewer Production',
                'password' => Hash::make(env('REVIEWER_PASSWORD', 'password123')),
                'email_verified_at' => now(),
            ]
        );

        Employee::firstOrCreate(
            ['user_id' => $reviewerProductionUser->id],
            [
                'outlet_id' => $outlet->id,
                'phone' => '081234567893',
                // Add required employee specific fields here based on your actual schema
            ]
        );
        
        // Note: Sample services, laundry items, and orders are assumed to be 
        // generated by other seeders or should be inserted here if needed.
    }
}
