// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'expense_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ExpenseModelImpl _$$ExpenseModelImplFromJson(Map<String, dynamic> json) =>
    _$ExpenseModelImpl(
      id: (json['id'] as num).toInt(),
      code: json['code'] as String,
      outletId: (json['outletId'] as num).toInt(),
      userId: (json['userId'] as num?)?.toInt(),
      employeeId: (json['employeeId'] as num?)?.toInt(),
      expenseAccountId: (json['expenseAccountId'] as num).toInt(),
      sourceAccountId: (json['sourceAccountId'] as num).toInt(),
      amount: (json['amount'] as num).toDouble(),
      date: json['date'] as String?,
      description: json['description'] as String?,
      attachment: json['attachment'] as String?,
      attachmentUrl: json['attachmentUrl'] as String?,
      hasAttachment: json['hasAttachment'] as bool? ?? false,
      status: json['status'] as String,
      approvedBy: (json['approvedBy'] as num?)?.toInt(),
      approvedAt: json['approvedAt'] as String?,
      rejectionReason: json['rejectionReason'] as String?,
      journalEntryId: (json['journalEntryId'] as num?)?.toInt(),
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      deletedAt: json['deletedAt'] as String?,
      formattedAmount: json['formattedAmount'] as String?,
      formattedDate: json['formattedDate'] as String?,
      statusLabel: json['statusLabel'] as String?,
      statusColor: json['statusColor'] as String?,
      isPending: json['isPending'] as bool? ?? false,
      isApproved: json['isApproved'] as bool? ?? false,
      isRejected: json['isRejected'] as bool? ?? false,
      canBeApproved: json['canBeApproved'] as bool? ?? false,
      canBeRejected: json['canBeRejected'] as bool? ?? false,
      canBeCancelled: json['canBeCancelled'] as bool? ?? false,
      outlet: json['outlet'] as Map<String, dynamic>?,
      employee: json['employee'] as Map<String, dynamic>?,
      user: json['user'] as Map<String, dynamic>?,
      expenseAccount: json['expenseAccount'] as Map<String, dynamic>?,
      sourceAccount: json['sourceAccount'] as Map<String, dynamic>?,
      approver: json['approver'] as Map<String, dynamic>?,
      journalEntry: json['journalEntry'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$$ExpenseModelImplToJson(_$ExpenseModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'code': instance.code,
      'outletId': instance.outletId,
      'userId': instance.userId,
      'employeeId': instance.employeeId,
      'expenseAccountId': instance.expenseAccountId,
      'sourceAccountId': instance.sourceAccountId,
      'amount': instance.amount,
      'date': instance.date,
      'description': instance.description,
      'attachment': instance.attachment,
      'attachmentUrl': instance.attachmentUrl,
      'hasAttachment': instance.hasAttachment,
      'status': instance.status,
      'approvedBy': instance.approvedBy,
      'approvedAt': instance.approvedAt,
      'rejectionReason': instance.rejectionReason,
      'journalEntryId': instance.journalEntryId,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'deletedAt': instance.deletedAt,
      'formattedAmount': instance.formattedAmount,
      'formattedDate': instance.formattedDate,
      'statusLabel': instance.statusLabel,
      'statusColor': instance.statusColor,
      'isPending': instance.isPending,
      'isApproved': instance.isApproved,
      'isRejected': instance.isRejected,
      'canBeApproved': instance.canBeApproved,
      'canBeRejected': instance.canBeRejected,
      'canBeCancelled': instance.canBeCancelled,
      'outlet': instance.outlet,
      'employee': instance.employee,
      'user': instance.user,
      'expenseAccount': instance.expenseAccount,
      'sourceAccount': instance.sourceAccount,
      'approver': instance.approver,
      'journalEntry': instance.journalEntry,
    };
