// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$OrderModelImpl _$$OrderModelImplFromJson(
  Map<String, dynamic> json,
) => _$OrderModelImpl(
  id: (json['id'] as num).toInt(),
  orderNumber: json['orderNumber'] as String,
  status: json['status'] as String,
  statusLabel: json['statusLabel'] as String?,
  statusBadgeVariant: json['statusBadgeVariant'] as String?,
  completionPercentage: (json['completionPercentage'] as num?)?.toInt() ?? 0,
  paymentStatus: json['paymentStatus'] as String,
  paymentStatusLabel: json['paymentStatusLabel'] as String?,
  paymentStatusBadgeVariant: json['paymentStatusBadgeVariant'] as String?,
  deliveryType: json['deliveryType'] as String?,
  deliveryTypeLabel: json['deliveryTypeLabel'] as String?,
  canPay: json['canPay'] as bool? ?? false,
  canScheduleDelivery: json['canScheduleDelivery'] as bool? ?? false,
  requiresPaymentBeforeDelivery:
      json['requiresPaymentBeforeDelivery'] as bool? ?? false,
  source: json['source'] as String?,
  sourceLabel: json['sourceLabel'] as String?,
  paymentMethod: json['paymentMethod'] as String?,
  customerId: (json['customerId'] as num).toInt(),
  customerAccountId: (json['customerAccountId'] as num?)?.toInt(),
  employeeId: (json['employeeId'] as num).toInt(),
  outletId: (json['outletId'] as num).toInt(),
  customerAddressId: (json['customerAddressId'] as num?)?.toInt(),
  updatedBy: (json['updatedBy'] as num?)?.toInt(),
  customer: json['customer'] == null
      ? null
      : CustomerModel.fromJson(json['customer'] as Map<String, dynamic>),
  customerAccount: json['customerAccount'] == null
      ? null
      : CustomerAccountModel.fromJson(
          json['customerAccount'] as Map<String, dynamic>,
        ),
  employee: json['employee'] == null
      ? null
      : EmployeeModel.fromJson(json['employee'] as Map<String, dynamic>),
  outlet: json['outlet'] == null
      ? null
      : OutletModel.fromJson(json['outlet'] as Map<String, dynamic>),
  customerAddress: json['customerAddress'],
  statusUpdater: json['statusUpdater'] == null
      ? null
      : EmployeeModel.fromJson(json['statusUpdater'] as Map<String, dynamic>),
  commissionLogs: json['commissionLogs'] as List<dynamic>? ?? const [],
  review: json['review'] == null
      ? null
      : OrderReviewModel.fromJson(json['review'] as Map<String, dynamic>),
  hasReview: json['hasReview'] as bool? ?? false,
  subtotal: (json['subtotal'] as num?)?.toDouble() ?? 0,
  pickupFee: (json['pickupFee'] as num?)?.toDouble() ?? 0,
  formattedPickupFee: json['formattedPickupFee'] as String?,
  deliveryFee: (json['deliveryFee'] as num?)?.toDouble() ?? 0,
  formattedDeliveryFee: json['formattedDeliveryFee'] as String?,
  discountAmount: (json['discountAmount'] as num?)?.toDouble() ?? 0,
  taxAmount: (json['taxAmount'] as num?)?.toDouble() ?? 0,
  totalAmount: (json['totalAmount'] as num?)?.toDouble() ?? 0,
  paidAmount: (json['paidAmount'] as num?)?.toDouble() ?? 0,
  remainingAmount: (json['remainingAmount'] as num?)?.toDouble() ?? 0,
  formattedSubtotal: json['formattedSubtotal'] as String?,
  formattedDiscountAmount: json['formattedDiscountAmount'] as String?,
  formattedTaxAmount: json['formattedTaxAmount'] as String?,
  formattedTotalAmount: json['formattedTotalAmount'] as String?,
  formattedPaidAmount: json['formattedPaidAmount'] as String?,
  formattedRemainingAmount: json['formattedRemainingAmount'] as String?,
  midtransOrderId: json['midtransOrderId'] as String?,
  midtransTransactionId: json['midtransTransactionId'] as String?,
  qrUrl: json['qrUrl'] as String?,
  orderDate: toDateTime(json['orderDate']),
  formattedOrderDate: json['formattedOrderDate'] as String?,
  estimatedCompletion: toDateTime(json['estimatedCompletion']),
  formattedEstimatedCompletion: json['formattedEstimatedCompletion'] as String?,
  actualCompletion: toDateTime(json['actualCompletion']),
  formattedActualCompletion: json['formattedActualCompletion'] as String?,
  pickupDate: toDateTime(json['pickupDate']),
  formattedPickupDate: json['formattedPickupDate'] as String?,
  deliveryDate: toDateTime(json['deliveryDate']),
  formattedDeliveryDate: json['formattedDeliveryDate'] as String?,
  deliverySchedule: toDateTime(json['deliverySchedule']),
  formattedDeliverySchedule: json['formattedDeliverySchedule'] as String?,
  deliveryAddress: json['deliveryAddress'] as String?,
  lastStatusUpdate: toDateTime(json['lastStatusUpdate']),
  formattedLastStatusUpdate: json['formattedLastStatusUpdate'] as String?,
  pickupType: json['pickupType'] as String?,
  pickupAddress: json['pickupAddress'] as String?,
  pickupSchedule: toDateTime(json['pickupSchedule']),
  formattedPickupSchedule: json['formattedPickupSchedule'] as String?,
  notes: json['notes'] as String?,
  internalNotes: json['internalNotes'] as String?,
  specialInstructions: json['specialInstructions'],
  orderItems: (json['orderItems'] as List<dynamic>?)
      ?.map((e) => OrderItemModel.fromJson(e as Map<String, dynamic>))
      .toList(),
  orderItemsCount: (json['orderItemsCount'] as num?)?.toInt() ?? 0,
  createdAt: toDateTime(json['createdAt']),
  updatedAt: toDateTime(json['updatedAt']),
  formattedCreatedAt: json['formattedCreatedAt'] as String?,
  formattedUpdatedAt: json['formattedUpdatedAt'] as String?,
  deletedAt: toDateTime(json['deletedAt']),
);

Map<String, dynamic> _$$OrderModelImplToJson(_$OrderModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'orderNumber': instance.orderNumber,
      'status': instance.status,
      'statusLabel': instance.statusLabel,
      'statusBadgeVariant': instance.statusBadgeVariant,
      'completionPercentage': instance.completionPercentage,
      'paymentStatus': instance.paymentStatus,
      'paymentStatusLabel': instance.paymentStatusLabel,
      'paymentStatusBadgeVariant': instance.paymentStatusBadgeVariant,
      'deliveryType': instance.deliveryType,
      'deliveryTypeLabel': instance.deliveryTypeLabel,
      'canPay': instance.canPay,
      'canScheduleDelivery': instance.canScheduleDelivery,
      'requiresPaymentBeforeDelivery': instance.requiresPaymentBeforeDelivery,
      'source': instance.source,
      'sourceLabel': instance.sourceLabel,
      'paymentMethod': instance.paymentMethod,
      'customerId': instance.customerId,
      'customerAccountId': instance.customerAccountId,
      'employeeId': instance.employeeId,
      'outletId': instance.outletId,
      'customerAddressId': instance.customerAddressId,
      'updatedBy': instance.updatedBy,
      'customer': instance.customer,
      'customerAccount': instance.customerAccount,
      'employee': instance.employee,
      'outlet': instance.outlet,
      'customerAddress': instance.customerAddress,
      'statusUpdater': instance.statusUpdater,
      'commissionLogs': instance.commissionLogs,
      'review': instance.review,
      'hasReview': instance.hasReview,
      'subtotal': instance.subtotal,
      'pickupFee': instance.pickupFee,
      'formattedPickupFee': instance.formattedPickupFee,
      'deliveryFee': instance.deliveryFee,
      'formattedDeliveryFee': instance.formattedDeliveryFee,
      'discountAmount': instance.discountAmount,
      'taxAmount': instance.taxAmount,
      'totalAmount': instance.totalAmount,
      'paidAmount': instance.paidAmount,
      'remainingAmount': instance.remainingAmount,
      'formattedSubtotal': instance.formattedSubtotal,
      'formattedDiscountAmount': instance.formattedDiscountAmount,
      'formattedTaxAmount': instance.formattedTaxAmount,
      'formattedTotalAmount': instance.formattedTotalAmount,
      'formattedPaidAmount': instance.formattedPaidAmount,
      'formattedRemainingAmount': instance.formattedRemainingAmount,
      'midtransOrderId': instance.midtransOrderId,
      'midtransTransactionId': instance.midtransTransactionId,
      'qrUrl': instance.qrUrl,
      'orderDate': instance.orderDate?.toIso8601String(),
      'formattedOrderDate': instance.formattedOrderDate,
      'estimatedCompletion': instance.estimatedCompletion?.toIso8601String(),
      'formattedEstimatedCompletion': instance.formattedEstimatedCompletion,
      'actualCompletion': instance.actualCompletion?.toIso8601String(),
      'formattedActualCompletion': instance.formattedActualCompletion,
      'pickupDate': instance.pickupDate?.toIso8601String(),
      'formattedPickupDate': instance.formattedPickupDate,
      'deliveryDate': instance.deliveryDate?.toIso8601String(),
      'formattedDeliveryDate': instance.formattedDeliveryDate,
      'deliverySchedule': instance.deliverySchedule?.toIso8601String(),
      'formattedDeliverySchedule': instance.formattedDeliverySchedule,
      'deliveryAddress': instance.deliveryAddress,
      'lastStatusUpdate': instance.lastStatusUpdate?.toIso8601String(),
      'formattedLastStatusUpdate': instance.formattedLastStatusUpdate,
      'pickupType': instance.pickupType,
      'pickupAddress': instance.pickupAddress,
      'pickupSchedule': instance.pickupSchedule?.toIso8601String(),
      'formattedPickupSchedule': instance.formattedPickupSchedule,
      'notes': instance.notes,
      'internalNotes': instance.internalNotes,
      'specialInstructions': instance.specialInstructions,
      'orderItems': instance.orderItems,
      'orderItemsCount': instance.orderItemsCount,
      'createdAt': instance.createdAt?.toIso8601String(),
      'updatedAt': instance.updatedAt?.toIso8601String(),
      'formattedCreatedAt': instance.formattedCreatedAt,
      'formattedUpdatedAt': instance.formattedUpdatedAt,
      'deletedAt': instance.deletedAt?.toIso8601String(),
    };
