// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'outlet_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$OutletModelImpl _$$OutletModelImplFromJson(Map<String, dynamic> json) =>
    _$OutletModelImpl(
      id: (json['id'] as num).toInt(),
      ownerId: (json['ownerId'] as num?)?.toInt(),
      name: json['name'] as String,
      code: json['code'] as String?,
      phone: json['phone'] as String?,
      email: json['email'] as String?,
      description: json['description'] as String?,
      isActive: json['isActive'] as bool,
      coinBalance: (json['coinBalance'] as num?)?.toInt() ?? 0,
      provinceId: (json['provinceId'] as num?)?.toInt(),
      provinceName: json['provinceName'] as String?,
      cityId: (json['cityId'] as num?)?.toInt(),
      cityName: json['cityName'] as String?,
      districtId: (json['districtId'] as num?)?.toInt(),
      districtName: json['districtName'] as String?,
      villageId: (json['villageId'] as num?)?.toInt(),
      villageName: json['villageName'] as String?,
      street: json['street'] as String?,
      fullAddress: json['fullAddress'] as String?,
      statusLabel: json['statusLabel'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      deletedAt: json['deletedAt'] as String?,
      categoriesCount: (json['categoriesCount'] as num?)?.toInt(),
      customersCount: (json['customersCount'] as num?)?.toInt(),
      employeesCount: (json['employeesCount'] as num?)?.toInt(),
      finesCount: (json['finesCount'] as num?)?.toInt(),
      laundryServicesCount: (json['laundryServicesCount'] as num?)?.toInt(),
      operationalDaysCount: (json['operationalDaysCount'] as num?)?.toInt(),
      membershipPlansCount: (json['membershipPlansCount'] as num?)?.toInt(),
      positionsCount: (json['positionsCount'] as num?)?.toInt(),
      ordersCount: (json['ordersCount'] as num?)?.toInt(),
      expensesCount: (json['expensesCount'] as num?)?.toInt(),
      journalEntriesCount: (json['journalEntriesCount'] as num?)?.toInt(),
      servicePackagesCount: (json['servicePackagesCount'] as num?)?.toInt(),
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      distance: (json['distance'] as num?)?.toDouble(),
      hasExposure: json['hasExposure'] as bool? ?? false,
      isActivated: json['isActivated'] as bool? ?? false,
      hasActiveExposure: json['hasActiveExposure'] as bool? ?? false,
      isExposureExpired: json['isExposureExpired'] as bool? ?? false,
      isCurrentlyOpen: json['isCurrentlyOpen'] as bool? ?? false,
      isCourierEnabled: json['isCourierEnabled'] as bool? ?? true,
      hasFreeShipping: json['hasFreeShipping'] as bool? ?? false,
      hasUnconditionalFreeShipping:
          json['hasUnconditionalFreeShipping'] as bool? ?? false,
      operationalStatus: json['operationalStatus'] == null
          ? null
          : OutletOperationalStatusModel.fromJson(
              json['operationalStatus'] as Map<String, dynamic>,
            ),
      todaySchedule: json['todaySchedule'] as Map<String, dynamic>?,
      nextOpenDay: json['nextOpenDay'] as Map<String, dynamic>?,
      averageRating: (json['averageRating'] as num?)?.toDouble(),
      reviewsCount: (json['reviewsCount'] as num?)?.toInt(),
      categories: (json['categories'] as List<dynamic>?)
          ?.map((e) => CategoryModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      operationalDays: (json['operationalDays'] as List<dynamic>?)
          ?.map((e) => OperationalDayModel.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$$OutletModelImplToJson(_$OutletModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'ownerId': instance.ownerId,
      'name': instance.name,
      'code': instance.code,
      'phone': instance.phone,
      'email': instance.email,
      'description': instance.description,
      'isActive': instance.isActive,
      'coinBalance': instance.coinBalance,
      'provinceId': instance.provinceId,
      'provinceName': instance.provinceName,
      'cityId': instance.cityId,
      'cityName': instance.cityName,
      'districtId': instance.districtId,
      'districtName': instance.districtName,
      'villageId': instance.villageId,
      'villageName': instance.villageName,
      'street': instance.street,
      'fullAddress': instance.fullAddress,
      'statusLabel': instance.statusLabel,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'deletedAt': instance.deletedAt,
      'categoriesCount': instance.categoriesCount,
      'customersCount': instance.customersCount,
      'employeesCount': instance.employeesCount,
      'finesCount': instance.finesCount,
      'laundryServicesCount': instance.laundryServicesCount,
      'operationalDaysCount': instance.operationalDaysCount,
      'membershipPlansCount': instance.membershipPlansCount,
      'positionsCount': instance.positionsCount,
      'ordersCount': instance.ordersCount,
      'expensesCount': instance.expensesCount,
      'journalEntriesCount': instance.journalEntriesCount,
      'servicePackagesCount': instance.servicePackagesCount,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'distance': instance.distance,
      'hasExposure': instance.hasExposure,
      'isActivated': instance.isActivated,
      'hasActiveExposure': instance.hasActiveExposure,
      'isExposureExpired': instance.isExposureExpired,
      'isCurrentlyOpen': instance.isCurrentlyOpen,
      'isCourierEnabled': instance.isCourierEnabled,
      'hasFreeShipping': instance.hasFreeShipping,
      'hasUnconditionalFreeShipping': instance.hasUnconditionalFreeShipping,
      'operationalStatus': instance.operationalStatus,
      'todaySchedule': instance.todaySchedule,
      'nextOpenDay': instance.nextOpenDay,
      'averageRating': instance.averageRating,
      'reviewsCount': instance.reviewsCount,
      'categories': instance.categories,
      'operationalDays': instance.operationalDays,
    };
