name: wash_wallet_cashier
description: "Aplikasi Laundry Terbaik di Indonesia"

publish_to: "none"

version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  wash_wallet_core:
    path: ../../packages/wash_wallet_core
  wash_wallet_domain:
    path: ../../packages/wash_wallet_domain
  wash_wallet_data:
    path: ../../packages/wash_wallet_data
  wash_wallet_ui:
    path: ../../packages/wash_wallet_ui
  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  connectivity_plus: ^7.0.0
  easy_localization: ^3.0.8
  form_validator: ^2.1.1
  pinput: ^5.0.2
  image_picker: ^1.2.0
  shimmer: ^3.0.0
  animations: ^2.0.11
  flutter_svg: ^2.0.10
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  modal_bottom_sheet: ^3.0.0
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  uuid: ^4.5.2
  get_it: ^9.2.0
  lottie: ^3.3.1
  flutter_bloc: ^9.1.1
  http_parser: ^4.1.2
  permission_handler: ^11.3.1
  print_bluetooth_thermal: ^1.1.9
  esc_pos_utils_plus: ^2.0.3
  dio: ^5.9.0
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  audioplayers: ^6.5.1
  pusher_channels_flutter: ^2.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.8
  intl: ^0.20.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  analyzer: ^7.6.0

  build_runner: ^2.5.4
  freezed: ^2.4.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.2

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/core/
    - assets/images/icons/
    - assets/sounds/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          style: italic
          weight: 900
